from .runtime import (
    ABI_VERSION,
    CONVERSATION_CLOSED_EVENT_TYPE,
    CONVERSATION_CREATED_EVENT_TYPE,
    FRONTEND_STATE_SNAPSHOT_EVENT_TYPE,
    LEDGER_DELTA_EVENT_TYPE,
    LEDGER_DELTA_SCHEMA,
    PUBLIC_RUNTIME_EVENT_TYPES,
    STATE_DELTA_EVENT_TYPE,
    STATE_DELTA_SCHEMA,
    WORKFLOW_EXECUTION_COMPLETED_EVENT_TYPE,
    WORKFLOW_RESOURCE_CHANGED_EVENT_TYPE,
    ConversationEntry,
    ConversationPosition,
    ConversationRegistry,
    ConversationRegistryAction,
    Runtime,
    RuntimeApp,
    RuntimeDiagnostic,
    RuntimeEventBus,
    RuntimeEventPump,
    RuntimeEventSubscription,
    RuntimeError,
    RuntimeHostBuilder,
    RuntimeStateError,
    RuntimeTimeout,
    UnsupportedCommand,
    conversation_id_from_event,
    is_ledger_delta_event,
    is_public_runtime_event,
    is_state_delta_event,
    is_workflow_event,
    ledger_delta_from_event,
    state_delta_from_event,
    workflow_id_from_event,
)
_NATIVE_EXPORTS = {
    "DEFAULT_RELEASE_TAG",
    "DEFAULT_REPOSITORY",
    "DEFAULT_RUNTIME_VERSION",
    "RuntimeArtifact",
    "UnsupportedRuntimePlatform",
    "ensure_runtime_library",
    "ensure_runtime_package",
    "resolve_runtime_library",
    "runtime_artifact",
    "runtime_platform_id",
}


def __getattr__(name: str):
    if name in _NATIVE_EXPORTS:
        from . import native

        value = getattr(native, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

__all__ = [
    "ABI_VERSION",
    "CONVERSATION_CLOSED_EVENT_TYPE",
    "CONVERSATION_CREATED_EVENT_TYPE",
    "FRONTEND_STATE_SNAPSHOT_EVENT_TYPE",
    "LEDGER_DELTA_EVENT_TYPE",
    "LEDGER_DELTA_SCHEMA",
    "PUBLIC_RUNTIME_EVENT_TYPES",
    "STATE_DELTA_EVENT_TYPE",
    "STATE_DELTA_SCHEMA",
    "WORKFLOW_EXECUTION_COMPLETED_EVENT_TYPE",
    "WORKFLOW_RESOURCE_CHANGED_EVENT_TYPE",
    "ConversationEntry",
    "ConversationPosition",
    "ConversationRegistry",
    "ConversationRegistryAction",
    "Runtime",
    "RuntimeApp",
    "RuntimeDiagnostic",
    "RuntimeEventBus",
    "RuntimeEventPump",
    "RuntimeEventSubscription",
    "RuntimeError",
    "RuntimeHostBuilder",
    "RuntimeStateError",
    "RuntimeTimeout",
    "UnsupportedCommand",
    "conversation_id_from_event",
    "is_ledger_delta_event",
    "is_public_runtime_event",
    "is_state_delta_event",
    "is_workflow_event",
    "ledger_delta_from_event",
    "state_delta_from_event",
    "workflow_id_from_event",
    "DEFAULT_RELEASE_TAG",
    "DEFAULT_REPOSITORY",
    "DEFAULT_RUNTIME_VERSION",
    "RuntimeArtifact",
    "UnsupportedRuntimePlatform",
    "ensure_runtime_library",
    "ensure_runtime_package",
    "resolve_runtime_library",
    "runtime_artifact",
    "runtime_platform_id",
]
